### ISSUE TITLE
Contribute to ggflags projects

### ISSUE THREAD

**Issue by Grelot** [rensa/ggflags#11]
Hi,
I would like to contribute to ggflags by adding icons for french town using their [IATA](https://en.wikipedia.org/wiki/IATA_airport_code) and doing the pictures myself

Is it possible ?

**Comment by jimjam-slam** [comment]
I'm interested in this, although I'd prefer to add a fairly full dataset of towns, rather than just doing a few towns. Perhaps you could fork ggflags and add the town flags yourself? I'd be happy to give you guidance on doing this!
