### ISSUE TITLE
Supporting R version 3.6

### ISSUE THREAD

**Issue by StefanMusch** [rensa/ggflags#12]
Hi.

Are you planning on adding support for the newest 3.6 version? I'm loving the package so far and would love to get it to work with the latest release. 

Thanks,

Stefan

**Comment by jimjam-slam** [comment]
Hi Stefan,

We're you able to fix the problem you were having? I haven't tested on. 3.6 yet, unfortunately!

**Comment by StefanMusch** [comment]
Hi. Yes sorry, I realized I was on version 6.1 (which ggflags didn't support). I scaled back to 6.0 and it worked just fine!

**Comment by jimjam-slam** [comment]
If there's a specific problem you had with it on 3.6.1, I'd love to know about it! AFAIK there's no reason it shouldn't continue to work with future R releases 😊
