### ISSUE TITLE
package ‘ggflags’ is not available (for R version 3.6.2)

### ISSUE THREAD

**Issue by SzymkowskiDev** [rensa/ggflags#13]
Warning in install.packages :
  package ‘ggflags’ is not available (for R version 3.6.2)

**Comment by Ralle8370** [comment]
I get this too:
"Warning in install.packages :
  package ‘ggflags’ is not available (for R version 3.6.3)"

**Comment by denironyx** [comment]
I also got this:
"Warning in install.packages :
package ‘ggflags’ is not available (for R version 3.6.3)"

**Comment by jimjam-slam** [comment]
Just to give y'all an update, I'm hoping to update the package soon but are having some problems with some of the dependent packages. Hoping to switch to a different backend, but it might take some time!

**Comment by JRamlov** [comment]
Hi @rensa - Hope all is going well with the package. Is there a work-around such that I can use it with an earlier version?

**Comment by jimjam-slam** [comment]
I'm sorry folks, I should've tweaked—`ggflags` is not actually on CRAN. You can install it using `remotes` or `devtools`:

```r
remotes::install_github('rensa/ggflags')
# or
devtools::install_github('rensa/ggflags')
```

Sorry for the confusion! I can't promise it'll install right now with the dependencies playing up, but give that a go 🙂
