### ISSUE TITLE
Package ‘ggflags’ is not available (for R version 4.0.2)

### ISSUE THREAD

**Issue by fedetiberti** [rensa/ggflags#21]
I'm trying to install the package and I get the warning that it is not available on CRAN. "Warning in install.packages :
  package ‘ggflags’ is not available (for R version 4.0.2)". Can I still install it from Github using remotes/devtools?

**Comment by jimjam-slam** [comment]
Hi there! Yes, `remotes` or `devtools` is the way to go. I'm hopping to get the next major release on CRAN 😊
