### ISSUE TITLE
Compatibility with R 4.2

### ISSUE THREAD

**Issue by jimjam-slam** [rensa/ggflags#22]
Reported by a user:

```r
set.seed(1234)
d <- data.frame(
  x = rnorm(50),
  y = rnorm(50),
  country = sample(c("ar","fr", "nz", "gb", "es", "ca", "lv", "qa"), 50, TRUE),
  stringsAsFactors = FALSE)

ggplot(d, aes(x = x, y = y, country = country, size = x)) +
  geom_flag() +
  scale_country() +
  scale_size(range = c(0, 15))
```

> Error in class(grobs) <- "gList" : attempt to set an attribute on NULL

**Comment by jimjam-slam** [comment]
I'v reproduced this on R 4.1! It could be a ggplot2 update issue...

**Comment by KGB-1991** [comment]
I just updated to R 4.2.1. and I get the same problem again:
`Error in class(grobs) <- "gList" : attempt to set an attribute on NULL`

Any idea why?

**Comment by jimjam-slam** [comment]
We're not entirely sure whether it's an R 4.2 issue or an issue with a ggplot2 change to be honest! Do you know if you also changed any packages when you upgraded, @GB-IHE? I've gotta get onto setting up some dev containers for testing!

**Comment by KGB-1991** [comment]
I did not change any packages, they were already up to date. I tried to go in to the source code for this package here on github for the package in order to try to find the error. However I was unsuccessful due to the number of dependencies in the code that I could not keep track of.

**Comment by KGB-1991** [comment]
Is there any fix comming? I would really like to use this package again.

**Comment by jimjam-slam** [comment]
I'm also for the wait, GB-IHE. I'd like to try and get a fix out over the holidays!

**Comment by jimjam-slam** [comment]
If I can carve the time out in the next week or two, I might actually fix this with a 1.0 release, which I hope in will be a major refactor using @coolbutuseless's [`{ggsvg}`](https://github.com/coolbutuseless/ggsvg).

**Comment by jimjam-slam** [comment]
(I'm trying to reproduce this again on R 4.2 and ggplot2 3.4.0 and failing! Maybe this is platform-specific?)

**Comment by KGB-1991** [comment]
Does it work for you? I can check tomorrow if that is the case...

**Comment by jimjam-slam** [comment]
It does currently! I'm wondering if this is maybe a platform-specific issue: I think last time I tried this it was on a Docker image (and so would've been Linux). This is a good reason for me to add ggflags to my R-Universe and get continuous integration going!

**Comment by KGB-1991** [comment]
I will test it today and try and report back then

**Comment by KGB-1991** [comment]
You are right - it seems it works now, at least my example. Strange - maybe they updated ggplot2?

**Comment by jimjam-slam** [comment]
I can't say, to be honest! The only thing I can think of was either (a) a dependency somewhere in the chain that broke it and then was updated again; or (b) an issue in R 4.1 that was fixed in R 4.2.

I might try to set up continuous integration to catch fleeting issues like this!

**Comment by gasparsuliansky** [comment]
Hi! I currently can not work with {ggflags} on R 4.1.3.

```
> install.packages("ggflags")
Warning in install.packages :
  package ‘ggflags’ is not available for this version of R
```

Is there a way I can use it in my current environment? 

PS: Big fan of the package!

**Comment by jimjam-slam** [comment]
Hi @GasparSuliansky! `ggflags` actually isn't available on CRAN—you'll need to install either `remotes` or `devtools` and then run `remotes::install_github("jimjam-slam/ggflags")`.

With my next update I'll be sure to update the docs with installation instructions! I'll also look into getting `ggflags` onto my R-Universe :)

**Comment by gasparsuliansky** [comment]
Thanks!
