### ISSUE TITLE
Is there a flag for Kosovo? 

### ISSUE THREAD

**Issue by liuyanguu** [rensa/ggflags#25]
Just a quick question. Many thanks.
Kosovo has ISO3Code of XKX and ISO2Code of XK

**Comment by jimjam-slam** [comment]
Hi @liuyanguu! Kosov's 2-letter code, `xk`, is valid :) Here's the flag:

<img width="39" alt="image" src="https://user-images.githubusercontent.com/6520659/216721743-b0e4dc9b-2857-4c8c-8743-18dc187934c5.png">

Note that in `ggflags` you presently need to use lowercase codes. (I hope to make the package more robust with the next release!)

**Comment by liuyanguu** [comment]
Thank you so much for your quick reply!
